### ISSUE TITLE
get_time_entries returns error

### ISSUE THREAD

**Issue by jonathanowitz** [ThinkR-open/togglr#10]
The following code: 
`get_time_entries(since = Sys.time() - weeks(10))`

returns this error
`Error in bind_rows_(x, .id) : Argument 10 must be length 1, not 2`

**Comment by jonathanowitz** [comment]
Any progress here?

**Comment by VincentGuyader** [comment]
can you try again with the current dev version ?

(can't reproduce this ...)

**Comment by jonathanowitz** [comment]
Uninstalled and then reinstalled via github, still getting the same issue. The get_current() function works, so it's not an account/API token issue. 

How can I help you solve this? Is there debugging or traceback I can do?

**Comment by VincentGuyader** [comment]
maybe you can give me you private token ( you can reset it after) I will try to find what is wrong

**Comment by jonathanowitz** [comment]
Hi there - finally got around to troubleshooting this. I think I've narrowed it down to when time entries have more than one tag. See if that can help you reproduce, if not I can share the actual data that I'm using.

**Comment by jonathanowitz** [comment]
I think it might also have to do with time entries that have a missing description. Actually upon further investigation, it happens whenever there's anything missing - a title, project, tag, or duration. This is especially true if you have the timer running when you call get_time_entries() with default parameters

**Comment by jonathanowitz** [comment]
Hi @VincentGuyader are you still working on this project?

**Comment by VincentGuyader** [comment]
hi, yes I work on it ( I just put the 0.1.33 version on CRAN a few day ago)
I encounter problems to reproduce your issue

I you can give me (in private) your token api, I will check.

Regards

**Comment by jonathanowitz** [comment]
What's the best way to reach you privately?

**Comment by VincentGuyader** [comment]
vincent@thinkr.fr
