### ISSUE TITLE
Download all time entries as a list

### ISSUE THREAD

**Issue by jonathanowitz** [ThinkR-open/togglr#7]
I would like to be able to download all of my time entries for a specific time period in a list format similar to how I am able to use get_current(). Maybe using this API call: 

https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md#get-time-entries-started-in-a-specific-time-range

**Comment by VincentGuyader** [comment]
good idea, I will check this asap.

Regards

**Comment by VincentGuyader** [comment]
please have a look to the `get_time_entries` function

regards
