### ISSUE TITLE
"help/togglr.rdb is corrupt" error message

### ISSUE THREAD

**Issue by jonathanowitz** [ThinkR-open/togglr#9]
I downloaded the newest version of togglr and now I'm getting the error message below when Rstudio does type ahead for set_toggl_api_token(): 

```
Error in fetch(key) : 
  lazy-load database 'mypath/togglr/help/togglr.rdb' is corrupt
```

I uninstalled and reinstalled, and am still getting the issue. Version information: 

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          4.2                         
year           2017                        
month          09                          
day            28                          
svn rev        73368                       
language       R                           
version.string R version 3.4.2 (2017-09-28)
nickname       Short Summer

**Comment by VincentGuyader** [comment]
please try to :  

erase togglr folder in `.libPaths()`
restart Rstudio
then devtools::install_github("ThinkR-open/togglr")

Regards

**Comment by jonathanowitz** [comment]
Fixed, thanks!
